### ISSUE TITLE
PR to include command line arguments

### ISSUE THREAD

**Issue by nilutpolkashyap** [MehmetOKUYAR/Yolo-Object-Detection-and-Distance-Measurement-with-Zed-camera#2]
Hi, I would like to open a pull request to include command line arguments in the code so that we can use custom weights file, cfg file, names file and svo path. 

please let me know.

**Comment by nilutpolkashyap** [comment]
@MehmetOKUYAR

**Comment by MehmetOKUYAR** [comment]
@nilutpolkashyap hi, No problem for me. How can I help you?

**Comment by nilutpolkashyap** [comment]
I will open a pull request. Thank you

**Comment by MehmetOKUYAR** [comment]
@nilutpolkashyap thank you so much your updates. Now it's really better repository

**Comment by nilutpolkashyap** [comment]
Thank you @MehmetOKUYAR
